In [1]:
# opencV代码块
import cv2
import tensorflow as tf
import os
import numpy as np

dir_mstar = 'D:\\QQdowanload\\2019-06-21 00-00-00-2019-08-20 12-00-00yuanpian\data\\3'

filenames = os.listdir(dir_mstar)
filelist = [os.path.join(dir_mstar, file) for file in filenames]
images2=[]
labels=[]
i=0
for file in filelist:
    
    aa=cv2.imread(file,0) 
    print(file)
    
    bb=cv2.resize(aa, (40, 40))
#     cv2.imshow('bb',bb)
    print(bb)#显示缩放后的图片
       
#     cv2.waitKey(0) 
    
    images2.append(bb)
    i+=1
    if i%2==0:
        labels.append(1)
    else:
        labels.append(0)
cc=np.array(images2,dtype='float')


labels=np.array(labels)

labels=labels.reshape(-1,1)

C:\Users\揍了个羊\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\揍了个羊\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\揍了个羊\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\揍了个羊\AppData\Roaming\Python\Python36\site-pack

D:\QQdowanload\2019-06-21 00-00-00-2019-08-20 12-00-00yuanpian\data\3\aaa.jpg
[[  0   1   0 ...   1   0   0]
 [  0   0   7 ...  10   0   0]
 [  0   2 227 ...  75   3   0]
 ...
 [  0   5 214 ... 229  38   0]
 [  0   1  27 ...  77   1   0]
 [  0   0   2 ...   3   0   0]]
D:\QQdowanload\2019-06-21 00-00-00-2019-08-20 12-00-00yuanpian\data\3\aaaaa.jpg
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   2 105 ... 118   4   0]
 ...
 [  0   9  34 ... 221   1   0]
 [  0   0   0 ...   6   0   0]
 [  0   0   0 ...   0   0   0]]
D:\QQdowanload\2019-06-21 00-00-00-2019-08-20 12-00-00yuanpian\data\3\axx.jpg
[[  0   0   1 ...   0   0   0]
 [  0   0   9 ...   0   0   0]
 [  0   1  83 ...   0   0   0]
 ...
 [  0  21 200 ... 145  15   0]
 [  0   0  54 ...  40   1   0]
 [  0   0   0 ...   3   0   0]]
D:\QQdowanload\2019-06-21 00-00-00-2019-08-20 12-00-00yuanpian\data\3\cc.jpg
[[  0   0   5 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   1 154 ...  91   0   0]
 ...
 [  0   0  33

In [7]:

from __future__ import print_function
from sklearn.model_selection import train_test_split
cc=cc.reshape(-1,40,40,1)
#该处由于没有labels所以就没有进行处理
train_images, test_images, train_labels, test_labels = train_test_split(cc, labels, test_size = 0.3)


# train_images, test_images= train_test_split(cc,test_size = 0.3)
print(train_images.shape,train_labels.shape)


import keras

from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D


import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"


epochs = 100


(7, 40, 40, 1) (7, 1)


Using TensorFlow backend.


In [8]:
# y_train = keras.utils.to_categorical(y_train, num_classes)
# y_test = keras.utils.to_categorical(y_test, num_classes)

model = Sequential()
model.add(Conv2D(40, (3, 3), padding='same',
                 input_shape=train_images.shape[1:]))
model.add(Activation('relu'))
model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Conv2D(64, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(1))
model.add(Activation('sigmoid'))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 40, 40, 40)        400       
_________________________________________________________________
activation_1 (Activation)    (None, 40, 40, 40)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 38, 38, 32)        11552     
_________________________________________________________________
activation_2 (Activation)    (None, 38, 38, 32)        0         
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 19, 19, 32)        0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 19, 19, 32)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 19, 19, 64)        18496     
__________

In [9]:
opt = keras.optimizers.rmsprop(lr=0.0001, decay=1e-6)

# Let's train the model using RMSprop
model.compile(loss='binary_crossentropy',
              optimizer=opt,
              metrics=['accuracy'])

train_images = train_images.astype('float32')
test_images = test_images.astype('float32')
train_images /= 255
test_images /= 255
model.fit(train_images, train_labels,
              batch_size=1,
              epochs=epochs,
              validation_data=(test_images, test_labels),
              shuffle=True)

Train on 7 samples, validate on 3 samples
Epoch 1/100
7/7 [==============================] - 1s 94ms/step - loss: 0.7020 - acc: 0.5714 - val_loss: 0.7163 - val_acc: 0.3333
Epoch 2/100
7/7 [==============================] - 0s 25ms/step - loss: 0.6932 - acc: 0.5714 - val_loss: 0.7262 - val_acc: 0.3333
Epoch 3/100
7/7 [==============================] - 0s 25ms/step - loss: 0.6829 - acc: 0.5714 - val_loss: 0.7347 - val_acc: 0.3333
Epoch 4/100
7/7 [==============================] - 0s 23ms/step - loss: 0.7022 - acc: 0.5714 - val_loss: 0.7381 - val_acc: 0.3333
Epoch 5/100
7/7 [==============================] - 0s 24ms/step - loss: 0.6544 - acc: 0.5714 - val_loss: 0.7509 - val_acc: 0.3333
Epoch 6/100
7/7 [==============================] - 0s 25ms/step - loss: 0.6751 - acc: 0.5714 - val_loss: 0.7557 - val_acc: 0.3333
Epoch 7/100
7/7 [==============================] - 0s 24ms/step - loss: 0.6634 - acc: 0.5714 - val_loss: 0.7748 - val_acc: 0.3333
Epoch 8/100
7/7 [==============================]

7/7 [==============================] - 0s 25ms/step - loss: 0.2805 - acc: 0.8571 - val_loss: 2.5300 - val_acc: 0.3333
Epoch 64/100
7/7 [==============================] - 0s 25ms/step - loss: 0.3444 - acc: 0.8571 - val_loss: 2.4568 - val_acc: 0.3333
Epoch 65/100
7/7 [==============================] - 0s 24ms/step - loss: 0.4373 - acc: 0.8571 - val_loss: 2.4725 - val_acc: 0.3333
Epoch 66/100
7/7 [==============================] - 0s 24ms/step - loss: 0.5523 - acc: 0.8571 - val_loss: 1.9599 - val_acc: 0.3333
Epoch 67/100
7/7 [==============================] - 0s 24ms/step - loss: 0.3125 - acc: 0.8571 - val_loss: 1.8623 - val_acc: 0.3333
Epoch 68/100
7/7 [==============================] - 0s 23ms/step - loss: 0.2470 - acc: 0.8571 - val_loss: 2.0101 - val_acc: 0.3333
Epoch 69/100
7/7 [==============================] - 0s 25ms/step - loss: 0.4547 - acc: 0.8571 - val_loss: 2.1237 - val_acc: 0.3333
Epoch 70/100
7/7 [==============================] - 0s 25ms/step - loss: 0.4813 - acc: 0.8571 - 