In [1]:
# opencV代码块
import cv2
import tensorflow as tf
import os
import numpy as np

dir_mstar = 'D:\\QQdowanload\\2019-06-21 00-00-00-2019-08-20 12-00-00yuanpian\data\\3'

filenames = os.listdir(dir_mstar)
filelist = [os.path.join(dir_mstar, file) for file in filenames]
images2=[]
labels=[]
i=0
for file in filelist:
    
    aa=cv2.imread(file,0) 
    print(file)
    
    bb=cv2.resize(aa, (40, 40))
#     cv2.imshow('bb',bb)
    print(bb)#显示缩放后的图片
       
#     cv2.waitKey(0) 
    
    images2.append(bb)
    i+=1
cc=np.array(images2,dtype='float')
#做个假数据 i是代表图片总量，10是假设有5个点，每个点有两个数据即x,y坐标
labels=np.random.rand(i,10)




labels.shape

C:\Users\揍了个羊\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\揍了个羊\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\揍了个羊\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\揍了个羊\AppData\Roaming\Python\Python36\site-pack

D:\QQdowanload\2019-06-21 00-00-00-2019-08-20 12-00-00yuanpian\data\3\aaa.jpg
[[  0   1   0 ...   1   0   0]
 [  0   0   7 ...  10   0   0]
 [  0   2 227 ...  75   3   0]
 ...
 [  0   5 214 ... 229  38   0]
 [  0   1  27 ...  77   1   0]
 [  0   0   2 ...   3   0   0]]
D:\QQdowanload\2019-06-21 00-00-00-2019-08-20 12-00-00yuanpian\data\3\aaaaa.jpg
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   2 105 ... 118   4   0]
 ...
 [  0   9  34 ... 221   1   0]
 [  0   0   0 ...   6   0   0]
 [  0   0   0 ...   0   0   0]]
D:\QQdowanload\2019-06-21 00-00-00-2019-08-20 12-00-00yuanpian\data\3\axx.jpg
[[  0   0   1 ...   0   0   0]
 [  0   0   9 ...   0   0   0]
 [  0   1  83 ...   0   0   0]
 ...
 [  0  21 200 ... 145  15   0]
 [  0   0  54 ...  40   1   0]
 [  0   0   0 ...   3   0   0]]
D:\QQdowanload\2019-06-21 00-00-00-2019-08-20 12-00-00yuanpian\data\3\cc.jpg
[[  0   0   5 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   1 154 ...  91   0   0]
 ...
 [  0   0  33

(10, 10)

In [2]:
#s数据集划分
from sklearn.model_selection import train_test_split
cc=cc.reshape(-1,40,40,1)
#该处由于没有labels所以就没有进行处理
train_images, test_images, train_labels, test_labels = train_test_split(cc, labels, test_size = 0.3)


# train_images, test_images= train_test_split(cc,test_size = 0.3)
print(train_images.shape,train_labels.shape)

(7, 40, 40, 1) (7, 10)


In [3]:

from __future__ import print_function
import keras

from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D


import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"


epochs = 100
model = Sequential()
model.add(Conv2D(40, (3, 3), padding='same',
                 input_shape=train_images.shape[1:]))
model.add(Activation('relu'))
model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Conv2D(64, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(10))

model.summary()


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 40, 40, 40)        400       
_________________________________________________________________
activation_1 (Activation)    (None, 40, 40, 40)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 38, 38, 32)        11552     
_________________________________________________________________
activation_2 (Activation)    (None, 38, 38, 32)        0         
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 19, 19, 32)        0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 19, 19, 32)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 19, 19, 64)        18496     
__________

Using TensorFlow backend.


In [4]:
opt = keras.optimizers.rmsprop(lr=0.0001, decay=1e-6)

# Let's train the model using RMSprop
model.compile(loss='mse',
              optimizer=opt,
              metrics=['accuracy'])

train_images = train_images.astype('float32')
test_images = test_images.astype('float32')
train_images /= 255
test_images /= 255
model.fit(train_images, train_labels,
              batch_size=1,
              epochs=epochs,
              validation_data=(test_images, test_labels),
              shuffle=True)

Train on 7 samples, validate on 3 samples
Epoch 1/100
7/7 [==============================] - 1s 86ms/step - loss: 0.1976 - acc: 0.0000e+00 - val_loss: 0.3139 - val_acc: 0.0000e+00
Epoch 2/100
7/7 [==============================] - 0s 22ms/step - loss: 0.1262 - acc: 0.1429 - val_loss: 0.2493 - val_acc: 0.3333
Epoch 3/100
7/7 [==============================] - 0s 23ms/step - loss: 0.1034 - acc: 0.1429 - val_loss: 0.2262 - val_acc: 0.3333
Epoch 4/100
7/7 [==============================] - 0s 24ms/step - loss: 0.1054 - acc: 0.1429 - val_loss: 0.2434 - val_acc: 0.3333
Epoch 5/100
7/7 [==============================] - 0s 24ms/step - loss: 0.1007 - acc: 0.1429 - val_loss: 0.2258 - val_acc: 0.0000e+00
Epoch 6/100
7/7 [==============================] - 0s 24ms/step - loss: 0.1182 - acc: 0.2857 - val_loss: 0.2497 - val_acc: 0.3333
Epoch 7/100
7/7 [==============================] - 0s 22ms/step - loss: 0.1152 - acc: 0.2857 - val_loss: 0.2367 - val_acc: 0.3333
Epoch 8/100
7/7 [===================

Epoch 63/100
7/7 [==============================] - 0s 24ms/step - loss: 0.0283 - acc: 0.5714 - val_loss: 0.1972 - val_acc: 0.3333
Epoch 64/100
7/7 [==============================] - 0s 24ms/step - loss: 0.0270 - acc: 0.2857 - val_loss: 0.1933 - val_acc: 0.3333
Epoch 65/100
7/7 [==============================] - 0s 22ms/step - loss: 0.0244 - acc: 0.7143 - val_loss: 0.1908 - val_acc: 0.3333
Epoch 66/100
7/7 [==============================] - 0s 24ms/step - loss: 0.0252 - acc: 0.7143 - val_loss: 0.1776 - val_acc: 0.3333
Epoch 67/100
7/7 [==============================] - 0s 23ms/step - loss: 0.0165 - acc: 0.7143 - val_loss: 0.1948 - val_acc: 0.3333
Epoch 68/100
7/7 [==============================] - 0s 23ms/step - loss: 0.0247 - acc: 0.8571 - val_loss: 0.1943 - val_acc: 0.3333
Epoch 69/100
7/7 [==============================] - 0s 23ms/step - loss: 0.0219 - acc: 0.7143 - val_loss: 0.2165 - val_acc: 0.3333
Epoch 70/100
7/7 [==============================] - 0s 23ms/step - loss: 0.0224 - a