In [1]:
# opencV代码块
import cv2
import tensorflow as tf
import os
import numpy as np

dir_mstar = 'D:\\QQdowanload\\2019-06-21 00-00-00-2019-08-20 12-00-00yuanpian\data\\3'

filenames = os.listdir(dir_mstar)
filelist = [os.path.join(dir_mstar, file) for file in filenames]
images2=[]
labels=[]
i=0
for file in filelist:
    
    aa=cv2.imread(file,0) 
    print(file)
    
    bb=cv2.resize(aa, (40, 40))
#     cv2.imshow('bb',bb)
    print(bb)#显示缩放后的图片
       
#     cv2.waitKey(0) 
    
    images2.append(bb)
    i+=1
cc=np.array(images2,dtype='float')
#做个假数据 i是代表图片总量，10是假设有5个点，每个点有两个数据即x,y坐标
labels=np.random.rand(i,20)




labels.shape

C:\Users\揍了个羊\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\揍了个羊\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\揍了个羊\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\揍了个羊\AppData\Roaming\Python\Python36\site-pack

D:\QQdowanload\2019-06-21 00-00-00-2019-08-20 12-00-00yuanpian\data\3\aaa.jpg
[[  0   1   0 ...   1   0   0]
 [  0   0   7 ...  10   0   0]
 [  0   2 227 ...  75   3   0]
 ...
 [  0   5 214 ... 229  38   0]
 [  0   1  27 ...  77   1   0]
 [  0   0   2 ...   3   0   0]]
D:\QQdowanload\2019-06-21 00-00-00-2019-08-20 12-00-00yuanpian\data\3\aaaaa.jpg
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   2 105 ... 118   4   0]
 ...
 [  0   9  34 ... 221   1   0]
 [  0   0   0 ...   6   0   0]
 [  0   0   0 ...   0   0   0]]
D:\QQdowanload\2019-06-21 00-00-00-2019-08-20 12-00-00yuanpian\data\3\axx.jpg
[[  0   0   1 ...   0   0   0]
 [  0   0   9 ...   0   0   0]
 [  0   1  83 ...   0   0   0]
 ...
 [  0  21 200 ... 145  15   0]
 [  0   0  54 ...  40   1   0]
 [  0   0   0 ...   3   0   0]]
D:\QQdowanload\2019-06-21 00-00-00-2019-08-20 12-00-00yuanpian\data\3\cc.jpg
[[  0   0   5 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   1 154 ...  91   0   0]
 ...
 [  0   0  33

(10, 20)

In [2]:
#s数据集划分
from sklearn.model_selection import train_test_split
cc=cc.reshape(-1,40,40,1)
#该处由于没有labels所以就没有进行处理
train_images, test_images, train_labels, test_labels = train_test_split(cc, labels, test_size = 0.3)


# train_images, test_images= train_test_split(cc,test_size = 0.3)
print(train_images.shape,train_labels.shape)

(7, 40, 40, 1) (7, 20)


In [3]:

from __future__ import print_function
import keras
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"

Using TensorFlow backend.


In [4]:
from keras.layers import Dense,Conv2D,MaxPooling2D,Flatten,Dropout,Activation,Input,Dot,multiply,ZeroPadding2D,Lambda,Reshape,concatenate,add,Flatten
from keras.models import Model

In [5]:
#做回归的到点的坐标
inputs=Input(shape=(40,40,1))
x=Conv2D(16,(3,3),padding='same')(inputs)
print(x.shape)
x=Activation('relu')(x)
x=Conv2D(32,(3,3),padding='same')(x)
x=Activation('relu')(x)
x=MaxPooling2D((2,2))(x)
x=Dropout(0.25)(x)
x=Conv2D(64,(3,3),padding='same')(x)
x=Activation('relu')(x)
x=Conv2D(64,(3,3),padding='same')(x)
x=Activation('relu')(x)
x=MaxPooling2D(2,2)(x)
x=Dropout(0.25)(x)
x=Flatten()(x)
x=Dense(52)(x)
predictions=Dense(20)(x)
opt = keras.optimizers.rmsprop(lr=0.0001, decay=1e-6)

model=Model(inputs=inputs,outputs=predictions)
model.compile(optimizer=opt,loss='mse',metrics=['acc'])
y=model.fit(train_images,train_labels,batch_size=1,
              epochs=20,
              validation_data=(test_images, test_labels),
              shuffle=True)
Y_pred=model.predict(test_images)
Y_pred

(?, 40, 40, 16)
Train on 7 samples, validate on 3 samples
Epoch 1/20
7/7 [==============================] - 1s 78ms/step - loss: 250.3668 - acc: 0.0000e+00 - val_loss: 30.3969 - val_acc: 0.3333
Epoch 2/20
7/7 [==============================] - 0s 7ms/step - loss: 142.1693 - acc: 0.1429 - val_loss: 25.6392 - val_acc: 0.0000e+00
Epoch 3/20
7/7 [==============================] - 0s 7ms/step - loss: 118.1142 - acc: 0.0000e+00 - val_loss: 13.0793 - val_acc: 0.3333
Epoch 4/20
7/7 [==============================] - 0s 7ms/step - loss: 102.6851 - acc: 0.0000e+00 - val_loss: 9.9229 - val_acc: 0.0000e+00
Epoch 5/20
7/7 [==============================] - 0s 7ms/step - loss: 73.4536 - acc: 0.1429 - val_loss: 8.5941 - val_acc: 0.0000e+00
Epoch 6/20
7/7 [==============================] - 0s 7ms/step - loss: 70.3707 - acc: 0.2857 - val_loss: 9.6663 - val_acc: 0.0000e+00
Epoch 7/20
7/7 [==============================] - 0s 7ms/step - loss: 51.1769 - acc: 0.1429 - val_loss: 6.9865 - val_acc: 0.0000e+00

array([[-0.7947719 , -0.36156413,  0.976563  ,  0.67706275, -0.15412629,
         0.88245547,  1.1958103 ,  0.04300353,  2.3753204 , -0.3438616 ,
         0.22246844,  0.9156539 ,  1.086321  ,  0.14316715,  0.08543287,
        -0.7641645 ,  2.189305  ,  1.0241998 ,  1.6980493 ,  0.827852  ],
       [ 0.5700859 , -0.5478462 ,  0.41613233, -1.1607072 ,  0.5267634 ,
         0.88771874,  1.4835494 , -0.439979  ,  1.0491705 ,  0.2622538 ,
         2.1750531 ,  0.6856421 , -0.48828715,  1.0190716 , -0.513712  ,
        -0.3786249 ,  1.545218  ,  0.41358706,  1.4206338 ,  1.675293  ],
       [-1.719356  ,  1.1261644 , -0.42821714,  0.9451484 , -0.4245649 ,
         2.949914  ,  3.2951648 , -1.4118975 ,  3.7268736 , -1.4287617 ,
        -0.4819728 ,  1.4659694 , -1.0214217 ,  1.0530499 ,  0.41042724,
         0.41054493,  0.41183084,  0.25613615,  3.5806243 , -0.4121939 ]],
      dtype=float32)

In [6]:
#做一个点的邻接矩阵 即边的关系 定义为若两个点之间有边 则为1 否则为0
import numpy as np
# 定义边关系
edges = np.array([[1, 2], [1, 6], [2, 1], [2, 3], [3, 2], [3, 4], [4,
                                                                   3], [4, 5],
                  [5, 4], [5, 6], [6, 5], [6, 7], [7, 6], [7, 1], [8, 9],
                  [9, 8], [9, 10], [10, 9]])
edges = edges - 1
# 做邻接矩阵
adj = np.ones(shape=(10, 10))

for i in edges:
    adj[i[0]][[i[1]]] = 2
adj

array([[1., 2., 1., 1., 1., 2., 1., 1., 1., 1.],
       [2., 1., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 1., 2., 1., 1., 1., 1., 1., 1.],
       [1., 1., 2., 1., 2., 1., 1., 1., 1., 1.],
       [1., 1., 1., 2., 1., 2., 1., 1., 1., 1.],
       [1., 1., 1., 1., 2., 1., 2., 1., 1., 1.],
       [2., 1., 1., 1., 1., 2., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 2., 1.],
       [1., 1., 1., 1., 1., 1., 1., 2., 1., 2.],
       [1., 1., 1., 1., 1., 1., 1., 1., 2., 1.]])

In [8]:
n1 = Y_pred
# 定义隐状态结点向量
hidden = np.random.random((3,10, 4))
n1=n1.reshape([-1, 10, 2])
n1.shape

(3, 10, 2)

# 方案1 

使用公式如下:adj 附近结点：fnodes全部相加/3 nodes+fnodes-->10,2 =nf adj diancheng nf-->10,2 =adjnf (adjnf+hidden)/2-->10,2 在flatten之后得20,1 后进行一维卷积

该方法并没有定义中间权值所以无需定义中间层 只需要对输入进行处理

In [9]:
# def concat(n1,h1):
#     #先找所有n1的附近的点
# for
# zhao每个点的邻近结点
s = []
b = []
c = []
for each in n1:
   
    for i, eeach in enumerate(each):
        if i == 0:
            s.append(each[1])
            #             print(each[1])
            s.append(each[5])

            z0 = np.array(s)
            s = []

        if i == 1:
            s.append(each[0])
            #             print(each[1])
            s.append(each[2])
            z1 = np.array(s)
            s = []
        if i == 2:
            s.append(each[1])
            s.append(each[3])
            z2 = np.array(s)
            s = []
        if i == 3:
            s.append(each[2])
            s.append(each[4])
            z3 = np.array(s)
            s = []
        if i == 4:
            s.append(each[3])
            s.append(each[5])
            z4 = np.array(s)
            s = []
        if i == 5:
            s.append(each[4])
            s.append(each[6])
            z5 = np.array(s)
            s = []
        if i == 6:
            s.append(each[5])
            s.append(each[0])
            z6 = np.array(s)
            s = []
        if i == 7:
            s.append(each[8])

            s.append(each[7])
            z7 = np.array(s)
            s = []
        if i == 8:
            s.append(each[7])
            s.append(each[9])
            z8 = np.array(s)
            s = []
        if i == 9:
            s.append(each[8])
            s.append(each[7])
            z9 = np.array(s)
            s = []

    b.append(z1)
    b.append(z2)
    b.append(z3)
    b.append(z4)
    b.append(z5)
    b.append(z6)
    b.append(z7)
    b.append(z8)
    b.append(z9)
    b.append(z0)
    c.append(b)
    b = []
c = np.array(c)
c.shape
print(c)
# 分别为batch 结点index 边数对应的结点index 维度
for each in c:
        for e in each:
            e[0]=(e[0]+e[-1])/2
                
c=c[:,:,0]
#得到附近结点的和向量
print(c.shape,n1.shape)

[[[[-0.7947719  -0.36156413]
   [-0.15412629  0.88245547]]

  [[ 0.976563    0.67706275]
   [ 1.1958103   0.04300353]]

  [[-0.15412629  0.88245547]
   [ 2.3753204  -0.3438616 ]]

  [[ 1.1958103   0.04300353]
   [ 0.22246844  0.9156539 ]]

  [[ 2.3753204  -0.3438616 ]
   [ 1.086321    0.14316715]]

  [[ 0.22246844  0.9156539 ]
   [-0.7947719  -0.36156413]]

  [[ 2.189305    1.0241998 ]
   [ 0.08543287 -0.7641645 ]]

  [[ 0.08543287 -0.7641645 ]
   [ 1.6980493   0.827852  ]]

  [[ 2.189305    1.0241998 ]
   [ 0.08543287 -0.7641645 ]]

  [[ 0.976563    0.67706275]
   [ 0.22246844  0.9156539 ]]]


 [[[ 0.5700859  -0.5478462 ]
   [ 0.5267634   0.88771874]]

  [[ 0.41613233 -1.1607072 ]
   [ 1.4835494  -0.439979  ]]

  [[ 0.5267634   0.88771874]
   [ 1.0491705   0.2622538 ]]

  [[ 1.4835494  -0.439979  ]
   [ 2.1750531   0.6856421 ]]

  [[ 1.0491705   0.2622538 ]
   [-0.48828715  1.0190716 ]]

  [[ 2.1750531   0.6856421 ]
   [ 0.5700859  -0.5478462 ]]

  [[ 1.545218    0.41358706]
   [-0.51

In [18]:
# 将fondes和node连接在一起 作为图卷积的输入
nz=np.concatenate((c,n1),axis=2)
nz.shape
nz=np.add(nz,hidden)
nz.shape

nz.shape

(3, 10, 4)

In [13]:
# a=np.random.random((3,10,2,2))
# print(a)
# for i in a:
#     for e in i:
#         e[0]=(e[0]+e[-1])/2
# a=a[:,:,0]
# type(a)
# 测试代码

In [17]:
# 编写自己的层 定义一个权值矩阵作为图卷积优化的一部分
from keras import backend as K
from keras.engine.topology import Layer

# class MyLayer(Layer):
#     def __init__(self,**kwargs):
# #         self.output_dim = output_dim
# #         if 'input_shape' not in kwargs and 'input_dim' in kwargs:
# #             kwargs['input_shape'] = (kwargs.pop('input_dim'),)
#         super(MyLayer, self).__init__(**kwargs)
        

#     def build(self, input_shape):
#         self.W = self.add_weight(shape=(input_shape[-1], 10),
#                                 initializer='random_uniform',name='hao',
#                                 trainable=True)
#         super(MyLayer, self).build()  # be sure you call this somewhere! 

#     def call(self, x, mask=None):
#         a=K.dot(x,self.W)
#         return K.dot(a,adj)
            

#     def get_output_shape_for(self, input_shape):
#         return tuple(input_shape[0] ,10)

class MyLayer(Layer):
 
    def __init__(self, output_dim,adj, **kwargs):
        self.adj=adj
        self.output_dim = output_dim
        super(MyLayer, self).__init__(**kwargs)
 
    def build(self, input_shape):
        # 为该层创建一个可训练的权重
        
        self.kernel = self.add_weight(name='kernel', 
                                      shape=(input_shape[-1], self.adj.shape[0]),
                                      initializer='uniform',
                                      
                                      trainable=True)
        super(MyLayer, self).build(input_shape)  # 一定要在最后调用它
 
    def call(self, x):
        a=K.dot(x,self.kernel)
        adj=K.constant(self.adj)
        print(adj)
        return K.dot(a,adj)
 
    def compute_output_shape(self, input_shape):
        return (input_shape[0], adj.shape[-1])



# class MyLayer2(Layer):

#     def __init__(self, output_dim, adj,**kwargs):
#         self.output_dim = output_dim
#         self.adj=adj
#         super(MyLayer2, self).__init__(**kwargs)
    

#     def build(self, input_shape):
#         # Create a trainable weight variable for this layer.
#         self.kernel = self.add_weight(name='kernel', 
#                                       shape=(input_shape[-1], self.output_dim),
#                                       initializer='uniform',
#                                       trainable=True)
        
#         super(MyLayer, self).build(input_shape)  # Be sure to call this at the end

#     def call(self, x):
        
#         a=K.dot(x,self.kernel)
#         print(1)
        
# #         adj=K.variable(self.adj)
# #         print(2)
# #         return K.dot(a,adj)
        
        

#     def compute_output_shape(self, input_shape):
#         return (input_shape[0], self.output_dim)

mylayer=MyLayer(10,adj)
print(1)


1


In [25]:
# class MyLayer2(Layer):

#     def __init__(self,**kwargs):
#          super(MyLayer2, self).__init__(**kwargs)
        

# #     def build(self, input_shape):
# #         # Create a trainable weight variable for this layer.
# #         self.kernel = self.add_weight(name='kernel', 
# #                                       shape=(input_shape[-1], self.output_dim),
# #                                       initializer='uniform',
# #                                       trainable=True)
        
# #         super(MyLayer, self).build(input_shape)  # Be sure to call this at the end

#     def call(self, x,y):
        
# #         a=K.dot(x,self.kernel)
# #         print(1)
        
# #         adj=K.variable(self.adj)
# #         print(2)
#         return K.dot(x,y)
        
        

#     def compute_output_shape(self):
#         return (x.shape[0], y.shape[1])


# print(x.shape)
def res(x):
#     print(type(x))
    x=K.expand_dims(x,axis=-1)
#     print(x.shape)
    return x
inputs=Input(shape=(10,4))
x=mylayer(inputs)
print(x.shape)
print(x.shape)
x=Lambda(res)(x)
print(x.shape)
x=ZeroPadding2D(padding=((1,1),(0,0)))(x)
x.shape
x=Conv2D(10,(3,10),strides=3,padding='valid')(x)
print(x.shape,2)
# 得到10个结点的隐状态向量
x=Reshape((10,4))(x)
print(3)
print(x.shape)
print(1)
x=add([x,inputs])
# def re(x):
#     x=K.reshape(x,(None,-1))
#     return x
def graphconv(z,inputs):
    z=mylayer(z)
    print(z.shape)
    print(z.shape)
    z=Lambda(res)(z)
    print(z.shape)
    z=ZeroPadding2D(padding=((1,1),(0,0)))(z)
    
    z=Conv2D(10,(3,10),strides=3,padding='valid')(z)
    print(z.shape)
    # 得到10个结点的隐状态向量
    z=Reshape((10,4))(z)
    z.shape
    z=add([z,inputs])
    return z
x=graphconv(x,inputs)
# x=Reshape([-1])(x)
print(x.shape)
# x=Lambda(re)(x)
x=Flatten()(x)
print(x.shape)
x=Dense(4)(x)
# print(x.shape)
p=Dense(4,activation='softmax')(x)
# 创建一个labels
labels=np.array([0,1,2])
labels=keras.utils.to_categorical(labels,num_classes=4)
model2=Model(inputs=inputs,outputs=p)
model2.compile(loss='categorical_crossentropy',optimizer='sgd',metrics=['acc'])
model2.fit(nz,labels,batch_size=1,epochs=100,verbose=1)
# x=Dense()(x)
model2.summary()
# x.shape

Tensor("my_layer_2_8/Const:0", shape=(10, 10), dtype=float32)
(?, 10, 10)
(?, 10, 10)
(?, 10, 10, 1)
(?, 4, 1, 10) 2
3
(?, 10, 4)
1
Tensor("my_layer_2_9/Const:0", shape=(10, 10), dtype=float32)
(?, 10, 10)
(?, 10, 10)
(?, 10, 10, 1)
(?, 4, 1, 10)
(?, 10, 4)
(?, ?)
Epoch 1/100
3/3 [==============================] - 0s 83ms/step - loss: 5.0189 - acc: 0.0000e+00
Epoch 2/100
3/3 [==============================] - 0s 1ms/step - loss: 2.6072 - acc: 0.3333
Epoch 3/100
3/3 [==============================] - 0s 1ms/step - loss: 1.7645 - acc: 0.3333
Epoch 4/100
3/3 [==============================] - 0s 1ms/step - loss: 0.9122 - acc: 0.6667
Epoch 5/100
3/3 [==============================] - 0s 997us/step - loss: 0.3162 - acc: 1.0000
Epoch 6/100
3/3 [==============================] - 0s 1ms/step - loss: 0.1156 - acc: 1.0000
Epoch 7/100
3/3 [==============================] - 0s 1ms/step - loss: 0.0578 - acc: 1.0000
Epoch 8/100
3/3 [==============================] - 0s 1ms/step - loss: 0.0357 - acc:

3/3 [==============================] - 0s 2ms/step - loss: 4.6407e-04 - acc: 1.0000
Epoch 85/100
3/3 [==============================] - 0s 1ms/step - loss: 4.5660e-04 - acc: 1.0000
Epoch 86/100
3/3 [==============================] - 0s 1ms/step - loss: 4.4930e-04 - acc: 1.0000
Epoch 87/100
3/3 [==============================] - 0s 1ms/step - loss: 4.4223e-04 - acc: 1.0000
Epoch 88/100
3/3 [==============================] - 0s 1ms/step - loss: 4.3533e-04 - acc: 1.0000
Epoch 89/100
3/3 [==============================] - 0s 1ms/step - loss: 4.2863e-04 - acc: 1.0000
Epoch 90/100
3/3 [==============================] - 0s 1ms/step - loss: 4.2217e-04 - acc: 1.0000
Epoch 91/100
3/3 [==============================] - 0s 2ms/step - loss: 4.1583e-04 - acc: 1.0000
Epoch 92/100
3/3 [==============================] - 0s 1ms/step - loss: 4.0965e-04 - acc: 1.0000
Epoch 93/100
3/3 [==============================] - 0s 1ms/step - loss: 4.0364e-04 - acc: 1.0000
Epoch 94/100
3/3 [=========================

In [113]:
# x=Lambda(res)(x)
# print(1)

In [184]:
keras.__version__

'2.2.4'

In [267]:
A=2

def iii():
    print(A)
iii()

2


In [ ]:
lambda

In [32]:
a=np.array([[1,2],[1]])
np.array((a[1]))

array([1])